@startuml foodshop-diagram-1

left to right direction
skinparam packageStyle rectangle
skinparam Shadowing false
skinparam actor {
    BorderColor OliveDrab
    FontName Courier
    FontColor OliveDrab
    BackgroundColor OliveDrab
}

' skinparam linetype ortho
skinparam usecase {
    BackgroundColor CornflowerBlue
    BorderColor CornflowerBlue
    FontColor Azure
    FontSize 20

    ArrowColor CornflowerBlue
}

actor customer
actor Owner

rectangle "Online Food shop overview"{
    customer -- (member register)
    customer -- (Login)
    (Login) -- Owner
    (Manage Goods) -- Owner
    customer -- (Make order)
    (Print slips) -- Owner
}
@enduml