@startuml Truck-company-1

left to right direction
skinparam packageStyle rectangle
skinparam Shadowing false
skinparam actor {
    BorderColor OliveDrab
    FontName Courier
    FontColor OliveDrab
    BackgroundColor OliveDrab
}

' skinparam linetype ortho
skinparam usecase {
    BackgroundColor CornflowerBlue
    BorderColor CornflowerBlue
    FontColor Azure
    FontSize 20

    ArrowColor CornflowerBlue
}

actor employee
actor Admin
actor "Truck Manager" as truckManager


rectangle "Truck rental company"{
    employee -- (Login)
    (Login) -- Admin
    (Manage employee) -- Admin
    usecase "Rent Truck(s)" as rentTruck
    employee -- rentTruck
    (Manage Truck Info) -- truckManager
    (Release a truck) -- truckManager
    (Invoice manage) -- truckManager
}
@enduml