@startuml diagram1

' ระบุ use case โดยใช้เครื่องหมายวงเล็บ
(First usecase)  

' ระบุ use case โดยใช้เครื่องหมายวงเล็บ และกำหนดชื่อให้เป็น UC2 
' ในการอ้างถึงในด้านล่างของโปรแกรม เราสามารถใช้ได้ทั้งชื่อ use case และชื่อตัวแปร
(Another usecase) as (UC2)

' สร้าง use case ชื่อ UC3 โดยใชีคีย์เวิร์ด (ไม่ใช้วงเล็บ) 
usecase UC3

' สร้าง use case ที่มีข้อความ 2 บรรทัด และกำหนดชื่อตัวแปรเป็น UC4
usecase (Last\nusecase) as UC4

@enduml