```puml
@startuml home1
left to right direction
skinparam rectangle{
    BorderColor LawnGreen
    FontColor Green
}
skinparam actor{
    BackgroundColor Green
    BorderColor Green
    FontColor Green
}
actor Customer
actor Owner
rectangle "Online Food shop overview"{
    Customer--(Member register)
    Customer--(Log in)
    (Manage Goods)--Owner
    (Log in) -- Owner
    Customer--(Make Order)
    (Print Slips)--Owner
}
skinparam usecase {
    BackgroundColor RoyalBlue
    BorderColor RoyalBlue
    FontColor white
    ArrowColor RoyalBlue
}
@enduml
```